from pathlib import Path
from typing import List

import cv2
import numpy as np
from scipy.ndimage import (
    center_of_mass, distance_transform_edt, label as nd_label, maximum_filter,
)

from cytoscan.config import ResearchConfig, CellDetectionConfig
from cytoscan.detections import CellDetection

"""
this module handles cell detections in a fluorescent frame (red dots on a black background).
achieved through simple thresholding and CV algorithms.

cell area in pixels is derived from the configured 'cell_diameter_um', provided by the researchers.

AI usage: detection and CV algorithms generated by AI
"""
def detect_cells(r_cfg: ResearchConfig, cd_cfg: CellDetectionConfig, fl_path: Path) -> List[CellDetection]:
    diameter_px = r_cfg.cell_diameter_um / r_cfg.pixel_size_um
    radius_px = diameter_px / 2.0
    expected_area_px = float(np.pi * radius_px * radius_px)

    img = cv2.imread(str(fl_path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return []
    if img.ndim == 3:
        gray = img[:, :, 2] # red channel (BGR)
    else:
        gray = img
    if gray.dtype != np.uint8:
        gray = cv2.normalize(gray, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    blurred = cv2.GaussianBlur(gray, (3, 3), 0)
    _, binary = cv2.threshold(blurred, cd_cfg.threshold, 255, cv2.THRESH_BINARY)
    if not binary.any():
        return []

    # distance transform: peaks at local maxima of the binary mask
    # an isolated cell has one peak, a double has two peaks one-diameter apart, etc etc
    dist = distance_transform_edt(binary)

    neighborhood = max(3, int(round(diameter_px)))
    if neighborhood % 2 == 0:
        neighborhood += 1
    max_dist = maximum_filter(dist, size=neighborhood)
    peak_mask = (dist == max_dist) & (dist >= 0.3 * radius_px)
    if not peak_mask.any():
        return []

    plateau_labels, n_plateaus = nd_label(peak_mask)
    plateau_centroids = center_of_mass(peak_mask, plateau_labels, range(1, n_plateaus + 1))
    peak_ys = np.array([c[0] for c in plateau_centroids])
    peak_xs = np.array([c[1] for c in plateau_centroids])

    # for per-cell area: count peaks per parent connected component, then
    # split the component's pixel area equally among them.
    n_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary, connectivity=8)
    peaks_per_component = np.zeros(n_labels, dtype=np.int32)
    component_per_peak = labels[peak_ys.astype(int), peak_xs.astype(int)]
    for cl in component_per_peak:
        peaks_per_component[cl] += 1

    min_area_px = max(1, int(round(0.25 * expected_area_px)))

    detections: List[CellDetection] = []
    next_label = 1
    for py, px, comp_label in zip(peak_ys, peak_xs, component_per_peak):
        if comp_label == 0:
            continue   # peak landed on background; shouldn't happen but guard
        comp_area = int(stats[comp_label, cv2.CC_STAT_AREA])
        n_peaks = max(1, int(peaks_per_component[comp_label]))
        per_cell_area = comp_area // n_peaks
        if per_cell_area < min_area_px:
            continue
        detections.append(CellDetection(
            centroid_x = float(px),
            centroid_y = float(py),
            area       = per_cell_area,
            label      = next_label,
        ))
        next_label += 1

    return detections
