experiment: "experiments/3000rpm_1min_Pax"
ilastik_model: "models/cells.ilp"
ilastik_exe: "/Applications/ilastik-1.4.1.post1-arm64-OSX.app/Contents/ilastik-release/run_ilastik.sh"

detection:
  channel_wall_degree: 2
  channel_interface_smoothing_factor: 32.0

  channel_wall_base_inset: 10
  channel_wall_max_inset_fraction: 0.175

output:
  export_visuals:
    enabled: "true"
    clear_existing: "true"        # complete output dir wipe on each run
    overwrite_existing: "true"     # overwrite existing output files with same name
    exported_frame : "brightfield"       # "brightfield" | "fluorescent" | "mixed"

    #toggles specific visuals
    cells: "true"
    channel_walls: "true"
    channel_walls_inset: "true"
    channel_interface: "true"
    roi: "true" #TODO
    
  export_report:
    enabled: "true" #TODO


      
